export const menu = [
    {
        id: 1,
        title: 'Buttermilk Pancakes',
        category: 'Breakfast',
        price: 15.99,
        img: '/images/item-1.jpeg',
        desc: `Fluffy buttermilk pancakes served with a drizzle of pure maple syrup, fresh berries, and a dollop of whipped cream. A breakfast classic that's perfect for starting your day with a sweet treat.`,
    },
    {
        id: 2,
        title: 'Diner Double',
        category: 'Lunch',
        price: 13.99,
        img: '/images/item-2.jpeg',
        desc: `Our signature Diner Double burger features two juicy beef patties cooked to perfection, topped with melted cheese, crispy bacon, fresh lettuce, and our secret sauce, all sandwiched between a toasted brioche bun.`,
    },
    {
        id: 3,
        title: 'Godzilla Milkshake',
        category: 'Shakes',
        price: 6.99,
        img: '/images/item-3.jpeg',
        desc: `Indulge in the Godzilla Milkshake, a monster of a shake with rich chocolate ice cream, crushed cookies, and a towering mountain of whipped cream. This shake is a sweet lover's dream come true.`,
    },
    {
        id: 4,
        title: 'Country Delight',
        category: 'Breakfast',
        price: 20.99,
        img: '/images/item-4.jpeg',
        desc: `Country Delight brings the charm of the countryside to your plate. Enjoy a hearty breakfast with fluffy scrambled eggs, crispy bacon, buttery toast, and a side of homemade preserves.`,
    },
    {
        id: 5,
        title: 'Egg Attack',
        category: 'Lunch',
        price: 22.99,
        img: '/images/item-5.jpeg',
        desc: `Get ready for an Egg Attack! This savory dish features perfectly poached eggs on a bed of sautéed spinach and mushrooms, drizzled with hollandaise sauce and served with toasted English muffins.`,
    },
    {
        id: 6,
        title: 'Oreo Dream',
        category: 'Shakes',
        price: 18.99,
        img: '/images/item-6.jpeg',
        desc: `Indulge in an Oreo Dream, a creamy shake loaded with chunks of chocolatey Oreo cookies. It's a sweet escape that will satisfy your cookie cravings.`,
    },
    {
        id: 7,
        title: 'Bacon Overflow',
        category: 'Breakfast',
        price: 8.99,
        img: '/images/item-7.jpeg',
        desc: `Bacon lovers, rejoice! Bacon Overflow is a plate filled with crispy strips of bacon, served alongside perfectly cooked eggs and a stack of fluffy pancakes. It's a breakfast feast.`,
    },
    {
        id: 8,
        title: 'American Classic',
        category: 'Lunch',
        price: 12.99,
        img: '/images/item-8.jpeg',
        desc: `Experience the taste of an American Classic with our juicy burger topped with fresh lettuce, tomatoes, onions, and a special sauce, all sandwiched in a sesame seed bun.`,
    },
    {
        id: 9,
        title: 'Quarantine Buddy',
        category: 'Shakes',
        price: 16.99,
        img: '/images/item-9.jpeg',
        desc: `Find comfort in our Quarantine Buddy shake, a blend of creamy vanilla ice cream and comforting cookie dough. It's the perfect treat to enjoy while staying cozy at home.`,
    },
];
